### ISSUE TITLE
[FEATURE] Add a filename formatter script

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/scripts#4]
### Description

There's a filename formatter that's being used already in various repositories, such as
the [**TypeScript repository**](https://github.com/TheAlgorithms/TypeScript) repository, the **[C](https://github.com/TheAlgorithms/C)/[C++](https://github.com/TheAlgorithms/C-Plus-Plus)** repositories, and soon other repositories as well.

This is not a Python script but more of a Bash script, I guess.
What do you think? Should we adjust it and add it to this repository? Thanks.

```bash
          IFS=$'\n'
          for fname in `find . -type f -name '*.cpp' -o -name '*.hpp'`
          do
            echo "${fname}"
            new_fname=`echo ${fname} | tr ' ' '_'`
            echo "      ${new_fname}"
            new_fname=`echo ${new_fname} | tr 'A-Z' 'a-z'`
            echo "      ${new_fname}"
            new_fname=`echo ${new_fname} | tr '-' '_'`
            echo "      ${new_fname}"
            if [ ${fname} != ${new_fname} ]
            then
              echo "      ${fname} --> ${new_fname}"
              git "mv" "${fname}" ${new_fname}
            fi
          done
```

CC: @raklaptudirm, @appgurueu, you might want to check this out as well.

**Comment by appgurueu** [comment]
Sure, why not
